### PR TITLE
feat(docs): Add illustrative image to README

### PR DESCRIPTION
**Pull request by rjvitorino**
Added an illustrative image to the README file to provide a visual example of using the 'refry' retry decorator. This image enhances the documentation by showing upfront a code snippet demonstrating the decorator's action. Updated the README to include this visual aid for better user understanding.

### CODE REVIEW

**Comment by rjvitorino** [comment]
Here's the image, to avoid having a link to my fork (didn't manage how to make it "transferrable"):

refry

**Comment by rjvitorino** [comment]
> Here's the image, to avoid having a link to my fork (didn't manage how to make it "transferrable"):
> 
> refry

Updated the README with the link from this comment, but am not sure if/when Github will throw it away after closing or deleting the pull request...

**Review by pydanny — APPROVED** [review]
Interesting, I've seen this more and more. While I prefer code examples, I know others have their own way to look at things. Let's do it!

**Comment by rjvitorino** [comment]
Great! I then recommend you to merge the approved Pull requests in order. #38 then #39 or #40

**Review by pydanny — APPROVED** [review]
LGTM

**Pull request merged**
