### PR TITLE
feat(logging): Enhance logging in retry decorator

### PR DESCRIPTION
**Pull request by rjvitorino**
This pull request enhances the logging within the retry decorator to provide more detailed insights into the retry behavior. The changes include logging the chosen backoff strategy, the backoff increment, whether jitter is enabled, and the number of retries. This additional logging information helps in tracking the backoff intervals and understanding the retry strategy more clearly, making debugging and monitoring easier.

### Changes Made

- Configured logging with logging.basicConfig(level=logging.INFO).
- Added a log statement to log the backoff strategy, increment, jitter status, and number of retries at the start of the wrapper.
- Updated retry attempt logs to include the backoff type and jitter status.
- Ensured exceptions and backoff intervals are clearly logged for easier debugging and monitoring.
- Removed redundant custom messages from raised exceptions and ensured they are logged instead.

### Related Issues
This pull request closes issue #7 by adding the necessary logging to track backoff strategies and retry attempts.

### Dependencies
This pull request **should be merged after** PR #38, which includes necessary refactoring and base improvements for the retry decorator.

### Checklist
- [x] Add logging configuration
- [x]  Log backoff strategy details
- [x]  Update retry attempt logs
- [x]  Remove redundant custom messages from raised exceptions
- [x]  Ensure backward compatibility

 
### Testing

- Verified that the retry decorator logs the backoff strategy and retry attempts correctly.
- Ensured exceptions are logged and re-raised without additional messages.
- Tested with various backoff strategies and jitter settings to confirm correct logging behaviour.

### CODE REVIEW

**Review by pydanny — APPROVED** [review]
Considering the volume of noise this can generate in projects, a future PR might make the logging level configurable.

**Comment by rjvitorino** [comment]
> Considering the volume of noise this can generate in projects, a future PR might make the logging level configurable.

Just pushed some changes for this @pydanny 😎

**Comment by pydanny** [comment]
Did you want to fix the merge conflict or would you like me to do it?

**Comment by rjvitorino** [comment]
If you can, I would appreciate it very much! I only meant to add the
capability you suggested

**Review by pydanny — APPROVED** [review]
LGTM

**Pull request merged**
